// One-time regeneration for JVS Bricks' August 2026 salary slips: they
// were auto-generated by the midnight-of-the-1st cron (00:00:0x on
// 2026-09-01), before the ADVANCE-only deduction bug was fixed (see
// salary.service.ts's generateSalarySlip — it now also deducts KHARCHI
// and MEDICAL payments made that month, not just ADVANCE). Regeneration
// is idempotent (unique index on personId+month, existing slip is
// updated in place, never duplicated), so this just brings the 9
// already-generated August slips in line with the corrected calculation.
//
// Run with: npx tsx src/scripts/regenerateAugustSalary.ts
import "dotenv/config";
import { generateForKiln } from "../services/salary.service";

const KILN_ID = "6a7741541033c0f439c33f9f"; // JVS Bricks

async function main() {
  const result = await generateForKiln(KILN_ID, "2026-08");
  console.log(JSON.stringify(result, null, 2));
  process.exit(0);
}

main().catch((err) => {
  console.error("Regeneration failed:", err);
  process.exit(1);
});
