import { Router } from "express";
import { authRouter } from "./auth.routes";
import { kilnRouter } from "./kiln.routes";
import { productionRouter } from "./production.routes";
import { stockRouter } from "./stock.routes";
import { syncRouter } from "./sync.routes";
import { personRouter } from "./person.routes";
import { attendanceRouter } from "./attendance.routes";
import { soilTripRouter } from "./soilTrip.routes";
import { landRouter } from "./land.routes";
import { soilContractRouter } from "./soilContract.routes";
import { jcbWorkLogRouter } from "./jcbWorkLog.routes";
import { expenseRouter } from "./expense.routes";
import { moldingRouter } from "./molding.routes";
import { wastageRouter } from "./wastage.routes";
import { gherRouter } from "./gher.routes";
import { stackingRouter } from "./stacking.routes";
import { stackingVehicleRouter } from "./stackingVehicle.routes";
import { nikasiRouter } from "./nikasi.routes";
import { reconciliationRouter } from "./reconciliation.routes";
import { complianceRouter } from "./compliance.routes";
import { dispatchRouter } from "./dispatch.routes";
import { fuelPurchaseRouter } from "./fuelPurchase.routes";
import { fuelLogRouter } from "./fuelLog.routes";
import { chamberGradingRouter } from "./chamberGrading.routes";
import { firingShiftRouter } from "./firingShift.routes";
import { kilnIncidentRouter } from "./kilnIncident.routes";
import { loadingEntryRouter } from "./loadingEntry.routes";
import { brickLoadingRouter } from "./brickLoading.routes";
import { workEntryRouter } from "./workEntry.routes";
import { soilArrivalRouter } from "./soilArrival.routes";
import { stockAuditRouter } from "./stockAudit.routes";
import { machineRouter } from "./machine.routes";
import { financialReportRouter } from "./financialReport.routes";
import { familyMemberRouter } from "./familyMember.routes";
import { inventoryRouter } from "./inventory.routes";
import { suppliedItemRouter } from "./suppliedItem.routes";
import { brickCategoryRouter } from "./brickCategory.routes";
import { fuelTypeRouter } from "./fuelType.routes";
import { kilnVehicleRouter } from "./kilnVehicle.routes";
import { paymentReceiptRouter } from "./paymentReceipt.routes";
import { financialOverviewRouter } from "./financialOverview.routes";
import { salaryRouter } from "./salary.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/kilns", kilnRouter);
apiRouter.use("/production", productionRouter);
apiRouter.use("/stock", stockRouter);
apiRouter.use("/sync", syncRouter);
apiRouter.use("/people", personRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/soil-trips", soilTripRouter);
apiRouter.use("/lands", landRouter);
apiRouter.use("/soil-contracts", soilContractRouter);
apiRouter.use("/jcb-work-logs", jcbWorkLogRouter);
apiRouter.use("/expenses", expenseRouter);
apiRouter.use("/molding", moldingRouter);
apiRouter.use("/wastage", wastageRouter);
apiRouter.use("/ghers", gherRouter);
apiRouter.use("/stacking", stackingRouter);
apiRouter.use("/stacking-vehicles", stackingVehicleRouter);
apiRouter.use("/nikasi", nikasiRouter);
apiRouter.use("/reconciliation", reconciliationRouter);
apiRouter.use("/compliance", complianceRouter);
apiRouter.use("/dispatch", dispatchRouter);
apiRouter.use("/fuel-purchases", fuelPurchaseRouter);
apiRouter.use("/fuel-logs", fuelLogRouter);
apiRouter.use("/chamber-gradings", chamberGradingRouter);
apiRouter.use("/firing-shifts", firingShiftRouter);
apiRouter.use("/incidents", kilnIncidentRouter);
apiRouter.use("/loading-entries", loadingEntryRouter);
apiRouter.use("/brick-loading", brickLoadingRouter);
apiRouter.use("/work-entries", workEntryRouter);
apiRouter.use("/soil-arrivals", soilArrivalRouter);
apiRouter.use("/stock-audits", stockAuditRouter);
apiRouter.use("/machines", machineRouter);
apiRouter.use("/financial-reports", financialReportRouter);
apiRouter.use("/family-members", familyMemberRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/supplied-items", suppliedItemRouter);
apiRouter.use("/brick-categories", brickCategoryRouter);
apiRouter.use("/fuel-types", fuelTypeRouter);
apiRouter.use("/kiln-vehicles", kilnVehicleRouter);
apiRouter.use("/payment-receipts", paymentReceiptRouter);
apiRouter.use("/financial-overview", financialOverviewRouter);
apiRouter.use("/salary", salaryRouter);
